### ISSUE TITLE
How to access the WEB Ui from other machines [BUG]

### ISSUE THREAD

**Issue by boivinx7** [Ankermgmt/ankermake-m5-protocol#159]
Is there a way to access the webUI from the IP of the machine, seems like the only way is trough localhost or 127.0.0.1 but i installed this on a VM, would need it to work from the IP address.

 - OS: Ubuntu 22.04
 - Browser : any, tried, Chrome, Brave, firefox and edge all latest versions

**Comment by anselor** [comment]
You just need to update the IP address flask binds to from 127.0.0.1 to 0.0.0.0.

**Comment by boivinx7** [comment]
Thanks
