### ISSUE TITLE
i installed python3 .but when i go over to : pip3 install -r requirements.txt ,then i get the message error requirements not found on ...........................ect

### ISSUE THREAD

**Issue by Jean0726** [Ankermgmt/ankermake-m5-protocol#45]
![github](https://user-images.githubusercontent.com/130203597/230850409-457199ed-29b8-46a5-bcf2-6b9eebf5d6f0.png)
![github 2](https://user-images.githubusercontent.com/130203597/230850449-ef8478e5-b093-4256-9388-dd49a4853899.png)

sorry had written on the quick tx at the end instead of txt but that doesn't change anything

**Comment by LazeMSS** [comment]
You did not checkout the code or not in the right folder

**Comment by Jean0726** [comment]
the folder of the repository  : or do i need to go to a specific folder of the repo

**Comment by chrivers** [comment]
Right now your prompt (powershell) is in `Desktop\Github`, but you need to be in the folder you got from github.

You need to be in the main folder of the repository, which is the one that has a file called `requirements.txt`

To change folder, type `cd <name>` to enter `<name>`. Use `cd ..` to go a level up.

**Comment by Jean0726** [comment]
I put the repo from github on the desktop, that was wrong ?

**Comment by chrivers** [comment]
Nothing wrong with that, as such.

However, where is the `requirements.txt` file located? In your screenshot, your command prompt is in the folder "Github" (which is a folder on your Desktop).

I imagine you have a folder inside "Github", where you have a copy of this repository?

If so, you need to enter that directory in your command prompt.

Let me know if that helps - if not, please try to describe exactly what you downloaded, how you unpacked, and what commands you tried (with screenshots if possible).

**Comment by Jean0726** [comment]
ok with the pip3 .....requirements.txt I've done it now ,but now i'm stuck here same problem:

Support for logging in with username and password is not yet supported, but an auth_token can be imported from the saved credentials found in login.json in Ankermake Slicer. See ankerctl.py config import -h for details:

Usage: ankerctl.py config import [OPTIONS] path/to/login.json

  Import printer and account information from login.json

  When run without filename, attempt to auto-detect login.json in default
  install location

Options:
  -h, --help  Show this message and exit.

**Comment by chrivers** [comment]
What problem is that?

The good news is that you can start the program now.

Did you read the message that you pasted here? In particular:

```
When run without filename, attempt to auto-detect login.json in default
install location
```

So, try to run `ankerctl.py config import`, and see if that works.

**Comment by Jean0726** [comment]
![03](https://user-images.githubusercontent.com/130203597/231148730-1ebd0d68-af22-415f-b8dd-908e85792130.png)
I have that now and what should I enter now

**Comment by Jean0726** [comment]
is that ok now i can start the webserver ?
![5](https://user-images.githubusercontent.com/130203597/231154066-33d3b257-c1ed-432f-8ddc-e387ff1c037a.png)

**Comment by Jean0726** [comment]
ok 
![6](https://user-images.githubusercontent.com/130203597/231169336-42e69079-43ce-4a1c-bed0-a7d3f3fcad1f.png)

**Comment by Jean0726** [comment]
and must save that now or what do i do now , ps you are more than helpfull

**Comment by Jean0726** [comment]
yes i did and followed the instructions also tested the connection to the octoprint is ok but it doesn't print nothing uploads the printer doesn't react. i pressed upload and print but nothing

**Comment by LazeMSS** [comment]
What does the shell/prompt say when uploading?

**Comment by chrivers** [comment]
Based on your other ticket, it looks like you at least got the installation working, so I'm closing this issue. Feel free to reopen if that's not the case.
