### ISSUE TITLE
Cert error when executing mqtt command but not from the ankerctl directory

### ISSUE THREAD

**Issue by dmbaio** [Ankermgmt/ankermake-m5-protocol#47]
I get the following error if I run the python file with an mqtt option, but only if I'm not CD'd into that directory.

![image](https://user-images.githubusercontent.com/59879282/231025904-25fc9ab6-0f51-48f0-9267-39ce8e514044.png)

**Comment by chrivers** [comment]
Thanks for reporting this - I'll see if I can get it fixed soon.

We need to add some code to the python script, to locate the certificate file, regardless of the current working directory

**Comment by thomasjpatterson** [comment]
Thanks @dmbaio, we've been furiously working behind the scenes and one of the features that will be upcoming is the ability to use a web interface to select your login.json file for use so you can have it anywhere. Once #59 is complete you'll have this capability.

**Comment by billyjbryant** [comment]
This is addressed by #71 and will be released with v1.0.0

**Comment by thomasjpatterson** [comment]
Ready to Ship.
