### ISSUE TITLE
everything is running now but i can't connect to the printer

### ISSUE THREAD

**Issue by Jean0726** [Ankermgmt/ankermake-m5-protocol#49]
![50](https://user-images.githubusercontent.com/130203597/232136997-4c3eb01e-7211-4aeb-8ab2-489e36f344de.png)
![33](https://user-images.githubusercontent.com/130203597/232080992-74b42b5a-58be-44bb-9b5d-125a888eb8c8.png)
webserver test  says ok  but nothing arrives at the printer when I upload it with prusa

**Comment by chrivers** [comment]
This can typically happen, if the computer that runs `ankerctl.py` is not on the same wifi as the printer, or if you have some sort of firewall running, that is blocking the traffic.

The official AnkerMake Slicer supports relay mode (where the traffic is sent to AWS (Amazon Cloud) and back to the printer) if the printer cannot be contacted directly.

We don't support relay mode (yet), so this is a limitation for now.

Does that help?

**Comment by austinrdennis** [comment]
I get the same issue, but I'm definitely on the same wifi network. Does this not play nice with mesh clients?

**Comment by chrivers** [comment]
@austinrdennis can you do a wireshark capture while attempting this? Wireshark should be started before ankerctl, to ensure we see all traffic.

**Comment by MEvansDCC** [comment]
I am also having the same issue. I've connected my laptop (running the webserver) and the Anker to the same separate access point. And unfortunately the printer is not doing anything. I can however get a response from the command : 
"python .\ankerctl.py mqtt monitor"
![image](https://user-images.githubusercontent.com/68226351/235903595-cd677656-376c-4357-8c78-9503d5ea88fe.png)

**Comment by kivinen** [comment]
This can also happen when the printers IP-address has changed, for example because the DHCP server decided to assign it different address than before. I think the current code still uses the ip-address it gets from the cloud and it can take days before the cloud backend gets up to date ip-address for the device.

So if you run config show and pppp lan-search and see if the ip-addresses are not same, if so then you need to manually edit the config file to fix the ip-address.

**Comment by billyjbryant** [comment]
This typically indicates that you have a communication problem with the printer. Either the printer is on a different network or your local firewall on your computer is preventing you from connecting.

**Comment by MEvansDCC** [comment]
Quite right! Failed at the first hurdle 😄 turned off firewall and it worked. So will need to make a rule.

**Comment by chrivers** [comment]
@MEvansDCC that's great to hear!

Unfortunately, the pppp protocol is tricky to firewall exactly. But at least, you can allow all UDP traffic, which covers all pppp, instead of allowing all protocols.
