### ISSUE TITLE
Documentation Review and Polish

### ISSUE THREAD

**Issue by thomasjpatterson** [Ankermgmt/ankermake-m5-protocol#63]
Currently, we have an install guide for installing from Git. Starting from 1.0.0, the docker version becomes a much more realistic option.

1) Rework/move/expand current install instructions into two explicit documents:
  - documentation/install-from-git.md
  - documentation/install-from-docker.md

2) Each of these files should contain a section about how to do initial setup (meaning, import config). The command line works a little differently for docker and git installs, but the web ui path should be exactly the same.

3) In general, we need to really focus the information on the front README.md. It needs to be shorter, more concise, and link to other sub-documents better than now.

**Comment by chrivers** [comment]
Merged in upcoming
